name:                arrow-lang
version:             0.0.0.1
github:              "githubuser/arrow-lang"
license:             BSD3
author:              "Ethan Brierley"
maintainer:          "incoming+efunb-arrow-lang-12293303-issue-@incoming.gitlab.com"
copyright:           "2019 Ethan Brierley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/arrow-lang#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- http-conduit
- aeson
- process
- terminal-size
- lens

default-extensions:
- OverloadedStrings
- ViewPatterns
- DeriveGeneric
- TemplateHaskell

library:
  source-dirs: src

executables:
  arrow-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arrow-lang

tests:
  arrow-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arrow-lang
